### ISSUE TITLE
Could we make event subscriber registration static for laziness

### ISSUE THREAD

**Issue by weaverryan** [doctrine/event-manager#12]
Hi guys!

While helping a friend debug an issue, I noticed that the event subscribers cannot be lazily loaded in the Connection object of  DBAL Connection. The reason is that the EventSubscriber:: getSubscribedEvents()` method is non-static. And so, the subscriber objects must be instantiated in order to load the EventManager, even if those subscribers are not ultimately needed.

From a high level, what do you think about making this method (or some new method) static? This is how Symfony's event subscriber (which is based off of Doctrine's) works, which allows for laziness.

Thanks!

**Comment by Ocramius** [comment]
Don't think laziness is a good enough reason to make the API static.

Few major down-sides:

 1. BC break in the API (even if we add a method to the interface)
 2. removes the ability to control the registered events from inside the event subscriber

Shouldn't the `EventManager` be lazy instead? That could be trivial to achieve, and would be an implementation detail rather than a public contract.

**Comment by weaverryan** [comment]
Yea, the BC break is a big enough problem to avoid this on its own, I agree. 

About the EventManager being lazy, that's a good idea... we might be able to inject something that doesn't even try to register the events internally until an event is dispatched. Good idea :)
